"""instance root_password

Revision ID: d5be03d3f4e9
Revises: 04b990d99fd0
Create Date: 2026-07-11 15:16:32.108070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5be03d3f4e9'
down_revision: Union[str, Sequence[str], None] = '04b990d99fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('root_password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'root_password')
    # ### end Alembic commands ###
